services:
  app:
    image: gabrielmarini123/fiborepo:fibotag
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./target/fibodemo-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "app.jar"]

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mydb
